const FETCH_NOTES_PENDING = 'FETCH_NOTES_PENDING';
const FETCH_NOTES_SUCCESS = 'FETCH_NOTES_SUCCESS';
const FETCH_NOTES_FAIL = 'FETCH_NOTES_FAIL';

const FETCH_NOTE_PENDING = 'FETCH_NOTE_PENDING';
const FETCH_NOTE_SUCCESS = 'FETCH_NOTE_SUCCESS';
const FETCH_NOTE_FAIL = 'FETCH_NOTE_FAIL';

const ADD_NOTE_PENDING = 'ADD_NOTE_PENDING';
const ADD_NOTE_SUCCESS = 'ADD_NOTE_SUCCESS';
const ADD_NOTE_FAIL = 'ADD_NOTE_FAIL';

const UPDATE_NOTE_PENDING = 'UPDATE_NOTE_PENDING';
const UPDATE_NOTE_SUCCESS = 'UPDATE_NOTE_SUCCESS';
const UPDATE_NOTE_FAIL = 'UPDATE_NOTE_FAIL';

const DELETE_NOTES_PENDING = 'DELETE_NOTES_PENDING';
const DELETE_NOTES_SUCCESS = 'DELETE_NOTES_SUCCESS';
const DELETE_NOTES_FAIL = 'DELETE_NOTES_FAIL';

const ADD_SELECTED_NOTE = 'ADD_SELECTED_NOTE';
const REMOVE_UNSELECTED_NOTE = 'REMOVE_UNSELECTED_NOTE';

const SELECT_ALL_NOTES = 'SELECT_ALL_NOTES';
const UNSELECT_ALL_NOTES = 'UNSELECT_ALL_NOTES';

const FILTER = 'FILTER';

const NAVIGATE_TO_PAGE = 'NAVIGATE_TO_PAGE';

const RESET_STORE = 'RESET_STORE';

export default {
    FETCH_NOTES_PENDING,
    FETCH_NOTES_SUCCESS,
    FETCH_NOTES_FAIL,
    FETCH_NOTE_PENDING,
    FETCH_NOTE_SUCCESS,
    FETCH_NOTE_FAIL,
    ADD_NOTE_PENDING,
    ADD_NOTE_SUCCESS,
    ADD_NOTE_FAIL,
    UPDATE_NOTE_PENDING,
    UPDATE_NOTE_SUCCESS,
    UPDATE_NOTE_FAIL,
    DELETE_NOTES_PENDING,
    DELETE_NOTES_SUCCESS,
    DELETE_NOTES_FAIL,
    ADD_SELECTED_NOTE,
    REMOVE_UNSELECTED_NOTE,
    SELECT_ALL_NOTES,
    UNSELECT_ALL_NOTES,
    FILTER,
    NAVIGATE_TO_PAGE,
    RESET_STORE,
};
