export const FETCH_NOTES_PENDING = 'FETCH_NOTES_PENDING';
export const FETCH_NOTES_SUCCESS = 'FETCH_NOTES_SUCCESS';
export const FETCH_NOTES_FAIL = 'FETCH_NOTES_FAIL';

export const ADD_NOTE_PENDING = 'ADD_NOTE_PENDING';
export const ADD_NOTE_SUCCESS = 'ADD_NOTE_SUCCESS';
export const ADD_NOTE_FAIL = 'ADD_NOTE_FAIL';

export const DELETE_NOTES_PENDING = 'DELETE_NOTES_PENDING';
export const DELETE_NOTES_SUCCESS = 'DELETE_NOTES_SUCCESS';
export const DELETE_NOTES_FAIL = 'DELETE_NOTES_FAIL';

export const ADD_SELECTED_NOTE = 'ADD_SELECTED_NOTE';
export const REMOVE_UNSELECTED_NOTE = 'REMOVE_UNSELECTED_NOTE';

export const SELECT_ALL_NOTES = 'SELECT_ALL_NOTES';
export const UNSELECT_ALL_NOTES = 'UNSELECT_ALL_NOTES';

export default { 
    FETCH_NOTES_PENDING,
    FETCH_NOTES_SUCCESS,
    FETCH_NOTES_FAIL,
    ADD_NOTE_PENDING, 
    ADD_NOTE_SUCCESS, 
    ADD_NOTE_FAIL, 
    DELETE_NOTES_PENDING, 
    DELETE_NOTES_SUCCESS, 
    DELETE_NOTES_FAIL,
    ADD_SELECTED_NOTE,
    REMOVE_UNSELECTED_NOTE,
    SELECT_ALL_NOTES,
    UNSELECT_ALL_NOTES,
};
